CC = gcc
CFLAGS = -g -Wall -Iinclude
LDFLAGS = -lm
TARGET = bin/genvi
SRCDIR = src
OBJDIR = obj
INCDIR = include
SRCS = $(wildcard $(SRCDIR)/*.c)
OBJS = $(patsubst $(SRCDIR)/%.c, $(OBJDIR)/%.o, $(SRCS))
DEPS = $(wildcard $(INCDIR)/*.h)
all: $(TARGET)
$(TARGET): $(OBJS)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)
	@echo "Build complete! Run with: ./$(TARGET)"
$(OBJDIR)/%.o: $(SRCDIR)/%.c $(DEPS)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@
clean:
	@rm -rf $(OBJDIR) $(TARGET)
	@echo "Project cleaned."
run: all
	@./$(TARGET) data/reference.fna data/sample_reads.fastq 2025-10-29T10:00:00 2025-10-29T10:15:00

.PHONY: all clean run